### ISSUE TITLE
Fault in mathematical prelimineries

### ISSUE THREAD

**Issue by chandramaulichak108** [geekpradd/Quantum-Computing-SoS#1]
In the section 2.3, in the properties of the inner product, the second point is wrong it should be,

<a_1x_1+a_2x_2 ,  y>=a_1<x_1,y>+a_2<x_2,y>

where x and y are vectors and a_1 and a_2 \in Field.

**Comment by geekpradd** [comment]
@chandramaulichak108  unfortunately this isn't the case. It's a matter of convention, the linearity property can be defined across either the first or the second element of the inner product and the math works out to be the same.
